name: Typo
description: Create a report to help us improve spelling and grammar on the Bloom docs
title: "[Typo] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: You can use this form to have typos found in the Bloom docs corrected.

  - type: input
    attributes:
      label: Describe the typo
      description: Enter a clear and concise description of what the typo is.
      placeholder: Typo description
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Please include a screenshot of the typo, as well as a link to the page with the typo.
    validations:
      required: true   

  - type: input
    attributes:
      label: Expected spelling
      description: What is the correct spelling?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: Add any other info or screenshots about the problem here.
    validations:
      required: false 
